#ifndef HWCONFIG_H_
#define HWCONFIG_H_

#include "driver/gpio.h"

#define HWCONFIG_TESTMODE (1)

#define HWCONFIG_OUTPUTBUS_COUNT (16)
#define HWCONFIG_OUTPUTAREA_COUNT (3)
#define HWCONFIG_OUTPUT_COUNT (HWCONFIG_OUTPUTBUS_COUNT*HWCONFIG_OUTPUTAREA_COUNT)

// Relay control BUS
#define HWCONFIG_RELAY_BUS_1_PIN GPIO_NUM_6
#define HWCONFIG_RELAY_BUS_2_PIN GPIO_NUM_7
#define HWCONFIG_RELAY_BUS_3_PIN GPIO_NUM_15
#define HWCONFIG_RELAY_BUS_4_PIN GPIO_NUM_16
#define HWCONFIG_RELAY_BUS_5_PIN GPIO_NUM_17
#define HWCONFIG_RELAY_BUS_6_PIN GPIO_NUM_18
#define HWCONFIG_RELAY_BUS_7_PIN GPIO_NUM_8
#define HWCONFIG_RELAY_BUS_8_PIN GPIO_NUM_2
#define HWCONFIG_RELAY_BUS_9_PIN GPIO_NUM_5
#define HWCONFIG_RELAY_BUS_10_PIN GPIO_NUM_9
#define HWCONFIG_RELAY_BUS_11_PIN GPIO_NUM_10
#define HWCONFIG_RELAY_BUS_12_PIN GPIO_NUM_11
#define HWCONFIG_RELAY_BUS_13_PIN GPIO_NUM_12
#define HWCONFIG_RELAY_BUS_14_PIN GPIO_NUM_13
#define HWCONFIG_RELAY_BUS_15_PIN GPIO_NUM_14
#define HWCONFIG_RELAY_BUS_16_PIN GPIO_NUM_1

#define HWCONFIG_RELAY_MOSA1 GPIO_NUM_40
#define HWCONFIG_RELAY_MOSA2 GPIO_NUM_41
#define HWCONFIG_RELAY_MOSA3 GPIO_NUM_42

// User output
#define HWCONFIG_LEDWS2812B GPIO_NUM_47

#define HWCONFIG_I2C_SDA GPIO_NUM_48
#define HWCONFIG_I2C_SCL GPIO_NUM_21

// Relay sensing and power
#define HWCONFIG_MASTERPWRRELAY_EN GPIO_NUM_4
#define HWCONFIG_MASTERPWRSENSE_IN GPIO_NUM_39
#define HWCONFIG_CONNSENSE_IN GPIO_NUM_37

// User input
#define HWCONFIG_ENCODERA_IN GPIO_NUM_43
#define HWCONFIG_ENCODERB_IN GPIO_NUM_44
#define HWCONFIG_ENCODERSW GPIO_NUM_38

#define HWCONFIG_SANITY_PIN GPIO_NUM_27
#define HWCONFIG_SANITY2_PIN GPIO_NUM_0

#endif